# Generated by Django 4.0.4 on 2022-07-07 16:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('run', models.IntegerField(primary_key=True, serialize=False, verbose_name='Rut')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo')),
                ('contrasena', models.CharField(max_length=20, verbose_name='Contraseña')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apaterno', models.CharField(max_length=20, verbose_name='Apellido paterno')),
                ('amaterno', models.CharField(max_length=20, verbose_name='Apellido materno')),
                ('celular', models.IntegerField(verbose_name='Celular')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Producto')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('descuento', models.IntegerField(default=0, verbose_name='Porcentaje de oferta')),
                ('foto', models.ImageField(upload_to='users/%Y/%m/%d/', verbose_name='Foto')),
                ('destacado', models.BooleanField(verbose_name='Producto destacado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plankton.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('free', 'Free'), ('donante', 'Donante')], max_length=10, verbose_name='Tipo suscripción')),
                ('inicio', models.DateField(default=datetime.date.today, verbose_name='Inicio suscripción')),
                ('final', models.DateField(default=datetime.date.today, verbose_name='Final suscripción')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Plankton.user')),
            ],
        ),
    ]
