# Generated by Django 4.0.4 on 2022-07-07 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Plankton', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='id',
        ),
        migrations.AlterField(
            model_name='membership',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Plankton.user'),
        ),
    ]
