# Generated by Django 4.0.4 on 2022-07-07 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Plankton', '0006_membership_idsub_alter_membership_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='idSub',
        ),
        migrations.AlterField(
            model_name='membership',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
